source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'VideoExample' do
    pod 'youtube-ios-player-helper', '~> 0.1.4'
    pod 'XCGLogger', '~> 6.0.2'
    pod 'Kingfisher', '~> 4.7'
    use_frameworks!
end
